# Generated by Django 3.1.4 on 2021-02-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_auto_20210205_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='review',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
