# Generated by Django 3.1.4 on 2021-02-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0005_place_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="placeid",
            field=models.CharField(max_length=180),
        ),
    ]
