# Generated by Django 3.1.4 on 2021-02-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0006_auto_20210210_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='couple',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='single',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
