# Generated by Django 3.1.5 on 2021-02-27 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0009_place_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
